import base64
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet

STATUS_LABEL = {"pass": "PASS", "warn": "REVIEW", "fail": "FAIL"}
STATUS_COLOR = {"pass": colors.HexColor("#2F6B4F"), "warn": colors.HexColor("#9C7C3D"), "fail": colors.HexColor("#A5312B")}


def build_pdf_report(
    product_name: str,
    verdict: str,
    field_results: list[dict],
    ingredient_flags: list[dict],
    annotated_image_b64: str | None,
    created_at: str,
) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=18)
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8.5, textColor=colors.grey)

    story = []
    story.append(Paragraph("PackCheck — Legal Metrology Compliance Report", title_style))
    story.append(Paragraph("Legal Metrology (Packaged Commodities) Rules, 2011 — automated inspection assessment", styles["Normal"]))
    story.append(Spacer(1, 8 * mm))

    verdict_color = STATUS_COLOR.get(verdict, colors.black)
    story.append(Paragraph(f"<b>Product:</b> {product_name}", styles["Normal"]))
    story.append(Paragraph(f"<b>Scanned:</b> {created_at}", styles["Normal"]))
    story.append(Paragraph(
        f'<b>Verdict:</b> <font color="{verdict_color.hexval()}">{STATUS_LABEL.get(verdict, verdict).upper()}</font>',
        styles["Normal"],
    ))
    story.append(Spacer(1, 6 * mm))

    if annotated_image_b64:
        try:
            img_bytes = base64.b64decode(annotated_image_b64)
            img_reader = ImageReader(io.BytesIO(img_bytes))
            iw, ih = img_reader.getSize()
            max_w = 160 * mm
            scale = min(1.0, max_w / iw)
            story.append(Image(io.BytesIO(img_bytes), width=iw * scale, height=ih * scale))
            story.append(Spacer(1, 6 * mm))
        except Exception:
            pass  # report still generates without the image if decoding fails

    story.append(Paragraph("Declaration checklist", styles["Heading2"]))
    table_data = [["Status", "Declaration", "Rule", "Note"]]
    for r in field_results:
        table_data.append([
            STATUS_LABEL.get(r["status"], r["status"]),
            r["label"],
            r["rule"],
            Paragraph(r["note"], styles["Normal"]),
        ])
    table = Table(table_data, colWidths=[45, 110, 60, 220])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#14231C")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F3EC")]),
    ]))
    story.append(table)
    story.append(Spacer(1, 6 * mm))

    if ingredient_flags:
        story.append(Paragraph("Flagged ingredients", styles["Heading2"]))
        ing_data = [["Severity", "Ingredient", "Reason", "Regulation"]]
        for flag in ingredient_flags:
            ing_data.append([
                flag["severity"].upper(),
                flag["matched_text"],
                Paragraph(flag["reason"], styles["Normal"]),
                Paragraph(flag["regulation"], small),
            ])
        ing_table = Table(ing_data, colWidths=[55, 80, 210, 90])
        ing_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#A5312B")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(ing_table)
        story.append(Spacer(1, 6 * mm))

    story.append(Paragraph(
        "This report was generated by an automated hackathon prototype. Font-size findings are estimated from "
        "photo pixel proportions and have not been calibrated against a physical reference. Ingredient flags are "
        "informational, based on FSSAI regulations and published health guidance — not a certified lab assay. "
        "Verify all findings before taking enforcement action.",
        small,
    ))

    doc.build(story)
    return buf.getvalue()
